<!doctype html>
<html>
    <head>
        <link href="../css/styles.css" rel="stylesheet" />
        <link href="../css/galleria.classic.css" rel="stylesheet" />
    </head>
    <body>
        <div class="galleria">
            <a href=""><img src="../images/nature-pic1.jpg" data-big="../images/nature-pic1.jpg"
                            data-title="Common Kingfisher (Alcedo atthis)"
                            data-description="The Common Kingfisher (Alcedo atthis) also known as Eurasian Kingfisher, or River Kingfisher, is a small kingfisher with seven subspecies recognized within its wide distribution across Eurasia and North Africa. It is resident in much of its range, but migrates from areas where rivers freeze in winter.
This sparrow-sized bird has the typical short-tailed, large-headed kingfisher profile; it has blue upperparts, orange underparts and a long bill. It feeds mainly on fish, caught by diving, and has special visual adaptions to enable it to see prey under water. The glossy white eggs are laid in a nest at the end of a burrow in a riverbank. The genus Alcedo comprises a number of small, exclusively fish-eating kingfishers. The Common Kingfisher’s closest relatives in the genus are three similar blue-backed, orange-breasted species, the Blue-eared, Half-collared and Blyth's Kingfishers. This species has the typical short-tailed, dumpy-bodied large-headed and long-billed kingfisher shape. The adult male of the western European subspecies, A. a. ispida has green-blue upperparts with pale azure-blue back and rump, a rufous patch by the bill base, and a rufous ear-patch. It has a green-blue neck stripe, white neck blaze and throat, rufous underparts, and a black bill with some red at the base. The legs and feet are bright red. It is about 16 centimetres (6.3 in) long with a wingspan of 25 cm (9.8 in), and weighs 34–46 grams (1.2–1.6 oz).
The female is identical in appearance to the male except that her lower mandible is orange-red with a black tip. The juvenile is similar to the adult, but with duller and greener upperparts and paler underparts. Its bill is black, and the legs are also initially black.
The flight of the Kingfisher is fast, direct and usually low over water. The short rounded wings whirr rapidly, and a bird flying away shows an electric-blue 'flash' down its back.
In North Africa, Europe and Asia north of the Himalayas this is the only small blue kingfisher. In south and southeast Asia it can be confused with six other small blue-and-rufous kingfishers, but the rufous ear patches distinguish it from all but juvenile Blue-eared Kingfisher; details of the head pattern may be necessary to differentiate the two species where both occur.
The Common Kingfisher has no song. The flight call is a short sharp whistle, chee, repeated two or three times. Anxious birds emit a harsh, shrit-it-it and nestlings call for food with a churring noise.
The Common Kingfisher is widely distributed over Europe, Asia, and North Africa, mainly south of 60°N. It is a common breeding species over much of its vast Eurasian range, but in North Africa it is mainly a winter visitor, although it is a scarce breeding resident in coastal Morocco and Tunisia. In temperate regions, this kingfisher inhabits clear, slow-flowing streams and rivers, and lakes with well-vegetated banks. It frequents scrubs and bushes with overhanging branches close to shallow open water in which it hunts. In winter it is more coastal, often feeding in estuaries or harbours and along rocky seashores. Tropical populations are found by slow-flowing rivers, in mangrove creeks and in swamps.
Common Kingfishers are important members of ecosystems and good indicators of freshwater community health. The highest densities of breeding birds are found in habitats with clear water, which permits optimal prey visibility, and trees or shrubs on the banks. These habitats have also the highest quality of water, so the presence of this bird confirms the standard of the water. Measures to improve water flow can disrupt this habitat, and in particular, the replacement of natural banks by artificial confinement greatly reduces the populations of fish, amphibians and aquatic reptiles, and waterside birds are lost. It can tolerate a certain degree of urbanisation, provided the water remains clean." data-link="google.com"></a>
                        <a href=""><img src="../images/Botaurus_stellaris.jpg" data-big="../images/Botaurus_stellaris.jpg"
                                        data-title="Eurasian Bittern (Botaurus stellaris)"
                                        data-description="The Eurasian Bittern or Great Bittern (Botaurus stellaris) is a wading bird of the heron family Ardeidae. It is one of the species to which the Agreement on the Conservation of African-Eurasian Migratory Waterbirds (AEWA) applies.
This species was first described as Ardea stellaris by Linnaeus in his Systema naturae in 1758. The genus name Botaurus was given by English naturalist James Francis Stephens and is the Latin for bittern, and also bull, because the bittern's call resembles the bellowing of a bull. The specific epithet, stellata, is the Latin for starry, in reference to its speckled plumage. Its folk names include 'barrel-maker', 'bog-bull', 'bog hen', 'bog-trotter' and 'mire drum', mainly with reference to its voice or habitat. The Norfolk name 'butterbump' refers to its high fat content when eaten as food.
Bitterns are thickset herons with bright, pale, buffy-brown plumage covered with dark streaks and bars, similar in appearance to the American Bittern, Botaurus lentiginosa. As its alternate name suggests, this species is the largest of the bitterns. The Eurasian or Great Bittern is 69–81 cm (27–32 in) in length, with a 100–130 cm (39–51 in) wingspan and a body mass of 0.87–1.94 kg (1.9–4.3 lb).
Distribution in Europe as a whole is estimated at 20-44,000 males. It usually inhabits Phragmites reedbeds. The population is declining in much of its temperate European and Asian range. It is resident in the milder west and south, but migrates south from areas where the water freezes in winter. In the UK, the main areas are Lancashire and East Anglia with an estimated 44 breeding pairs. In Ireland it died out as a breeding species in the mid-19th century, but in 2011 a single bird was spotted in County Wexford and there have been a number of subsequent sightings.
Usually solitary, the Great Bittern forages in reedbeds, walking stealthily or remaining still above a body of water where prey may occur. If it senses that it has been seen, it points its bill directly upwards and becomes motionless so that its cryptic plumage causes it to blend into the surrounding reeds: an action known as bitterning. It is most active at dawn and dusk.
Males are polygamous with each mating with up to five females. The nest is built in the previous year's standing reeds and consists of a platform some 30 cm across. Four or five eggs are laid in late March and April and incubated by the female bird. After hatching, the chicks spend about two weeks in the nest and then disperse amongst the reeds.
Bitterns feed on fish, eels, amphibians and invertebrates, hunting along the reed margins in shallow water.
" data-link=""></a>
            <a href=""><img src="../images/nature-pic2.jpg" data-big="../images/nature-pic2.jpg"
                                                     data-title="Black Stork (Ciconia nigra)"
                                                     data-description="The Black Stork (Ciconia nigra) is a large wading bird in the stork family Ciconiidae. It is a widespread, but uncommon, species that breeds in the warmer parts of Europe (predominantly in central and eastern regions), across temperate Asia and Southern Africa. This is a shy and wary species, unlike the closely related White Stork. It is seen in pairs or small flocks—in marshy areas, rivers or inland waters. The Black Stork feeds on amphibians and insects.
The typical storks (Ciconia) include the White Stork and six other extant species, which are characterised by straight bills and mainly black and white plumage. Within the genus Ciconia, the Black Stork's closest relatives are the other European species, the White Stork and its former subspecies, the black-billed Oriental White Stork of east Asia. 
Slightly smaller than the White Stork, the Black Stork is a large bird, 95 to 100 cm (37–39 in) in length with a 145–155 cm (5 ft) wingspan, and weighing around 3 kilograms (6.6 lb). They can stand as tall as 102 cm (40 in). Like all storks, it has long legs, a long neck, and a long, straight, pointed beak. The plumage is all black with a purplish green sheen, except for the white lower breast, belly, axillaries and undertail coverts. The breast feathers are long and shaggy forming a ruff which is used in some courtship displays. The bare skin around its eyes is red, as are its red bill and legs. The sexes are identical in appearance, except that males are larger than females on average.
The juvenile resembles the adult in plumage pattern, but the areas corresponding to the adult black feathers are browner and less glossy. The scapulars, wing and upper tail coverts have pale tips. The legs, bill, and bare skin around the eyes are greyish green. It may be confused with the juvenile Yellow-billed Stork, but the latter has a paler wings and mantle, longer bill, and white under the wings.
It walks slowly and steadily on the ground. Like all storks, it flies with its neck outstretched. It has a rasping call, but rarely indulges in mutual bill-clattering when adults meet at the nest.
Preferring more wooded areas than the better known White Stork, the Black Stork breeds in large marshy wetlands with interspersed coniferous or broadleaved woodlands, but also inhabits hills and mountains with sufficient network of creeks. It does inhabit more areas in the Caspian lowlands.
The Black Stork is a strong migrant, wintering in tropical Africa and India. A broad-winged soaring bird, the Black Stork is assisted by thermals of hot air for long distance flight, although are less dependent on them than the White Stork. Since thermals only form over land, storks, together with large raptors, must cross the Mediterranean at the narrowest points, and many Black Storks can be seen going through the Bosporus. They fly approximately 100 to 250 km a day with daily maxima up to 500 km.
The Black Stork builds a stick nest high in trees or on cliffs. It nests in Central Europe in April to May, and is a winter visitor to northern India, Nepal east to Myanmar.
"/></a>
            <a href=""><img src="../images/Limosa_lapponica.jpg" data-big="../images/Limosa_lapponica.jpg"
                            data-title="Bar-tailed Godwit (Limosa lapponica)"
                            data-description="The Bar-tailed Godwit (Limosa lapponica) is a large wader in the family Scolopacidae, which breeds on Arctic coasts and tundra mainly in the Old World, and winters on coasts in temperate and tropical regions of the Old World. Its migration is the longest known non-stop flight of any bird and also the longest journey without pausing to feed by any animal.
The Bar-tailed Godwit is a relatively short-legged species of godwit. The bill-to-tail length is 37–41 cm, with a wingspan of 70–80 cm. Males average smaller than females but with much overlap; males weigh 190–400 g, while females weigh 260–630 g; there is also some regional variation in size. The adult has blue-grey legs and a very long dark bill with a slight upward curve and pink at the tip. The neck, breast and belly are unbroken brick red in breeding plumage, off white in winter. The back is mottled grey.
It is distinguished from the Black-tailed Godwit (Limosa limosa) by its barred, rather than wholly black, tail and a lack of white wing bars.
It forages by probing in mudflats or marshes. It may find insects by sight in short vegetation. It eats mainly insects and crustaceans, but also parts of aquatic plants.
The Bar-tailed Godwit is a non-breeding migrant in Australia. Breeding take place each year in Scandinavia, northern Asia, and Alaska. The nest is a shallow cup in moss sometimes lined with vegetation. Both sexes share incubation of the eggs and care for the young.
Protection: The Bar-tailed Godwit is one of the species to which the Agreement on the Conservation of African-Eurasian Migratory Waterbirds (AEWA) applies."/></a>
            <a href=""><img src="../images/Aythya_marila.jpg" data-big="../images/Aythya_marila.jpg"
                            data-title="Greater Scaup (Aythya marila)"
                            data-description="Планинска потапница (Aythya marila) е представител на семейство Патицови, разред Гъскоподобни, със средни размери и плътно набито телосложение. Тежи между 700 и 1300 g. Дължина на тялото 40—51 cm, размах на крилете около 75 cm. Има изразен полов диморфизъм. Плува и се гмурка добре. Лети бързо, от водата излита леко. На територията на България е защитен вид. Обитава сладководни езера и реки, гъсто обрасли с водна растителност. Понякога се среща и в близост до соленоводни басейни. Храни се поравно с растителна и животинска храна: дребни мекотели, личинки на насекоми, ракообразни, дребна риба, корени, листа и семена на водни растения. Моногамна птица. Гнездото си построява винаги в непосредствена близост до водата, често пъти на малки островчета или купчини стара тръстика. Снася от 6 до 13 мръсно зеленикави яйца с размери 62 х 40 mm и маса средно 67 g. Мъти 24—28 дни само женската. Малките се излюпват достатъчно развити за да могат да се придвижват и хранят самостоятелно.The Greater Scaup (Aythya marila), just Scaup in Europe, or colloquially 'Bluebill' in North America for its bright blue bill, is a mid-sized diving duck though it is larger than the closely related Lesser Scaup. It is a circumpolar species, which means that its range circles one of Earth's poles. It spends the summer months breeding in Alaska, northern Canada, Siberia, and the northernmost reaches of Europe. During the winter, it migrates south down the coasts of North America, Europe, and Japan.
Drake Greater Scaup are larger and have more rounded heads than females; they have a bright blue bill and yellow eyes. They have dark heads with a glossy green tint, white undersides and wings with white on the tips. The females are mostly brown, with white bands located on their wingtips. They have a blue bill that is slightly duller then the drake's.
Greater Scaup nest near water, typically on islands in northern lakes or on floating mats of vegetation. They begin breeding at age two, but start building nests in the first year. The drakes have a complex courtship procedure, which takes place on the return migration to the summer breeding grounds and concludes with the formation of monogamous pairs. Females lay a clutch of six to nine olive-buff colored eggs. The eggs hatch in 24 to 28 days. The down-covered ducklings are able to follow their mother in her search for food immediately after hatching.
Greater Scaup eat aquatic mollusks, plants, and insects, which they obtain by diving underwater. They form large groups, called 'rafts', that can number in the thousands. Their main threat is human development, although they are preyed upon by owls, skunks, raccoons, foxes, coyotes, and humans. Greater Scaup populations have been declining since the 1980s; however, they are still listed as a species of least concern on the IUCN Red List.
The adult Greater Scaup is 39–56 cm (15–22 in) long with a 71–84 cm (28–33 in) wingspan and a body mass of 726–1,360 g (1.601–2.998 lb). It has a blue bill and yellow eyes and is 20% heavier and 10% longer than the closely related Lesser Scaup. The male has a dark head with a green sheen, a black breast, a light back, a black tail, and a white underside. The drake or male Greater Scaup is larger and has a more rounded head than the female. The drake's belly and flanks are a bright white. Its neck, upper chest, and tail feathers are a glossy black, while its lower flanks are gray. The drake also has a white speculum on its wings. The adult female has a white band and brown oval shaped patches at the base of the bill, which is a slightly duller shade of blue than the drake's bill. Females have grey on both their legs and feet. They have a brown body and head, with white bands on their wingtips. Juvenile Greater Scaup look similar to adult females. The Greater Scaup drake's eclipse plumage looks similar to its breeding plumage, except the pale parts of the plumage are a buffy gray. Distinguishing Greater from Lesser scaups can be extraordinarily difficult in the field, especially in terms of plumage, although (depending on posture) their general shape is slightly different.
The Greater Scaup dive to obtain food, which they eat on the surface. They mainly eat mollusks, aquatic plants, and aquatic insects. During the summer months, the Greater Scaup will eat small aquatic crustaceans. There is a report of four Greater Scaups swallowing leopard frogs (with body length about 2.0 in), which they dredged out of a roadside freshwater pond. In freshwater ecosystems, the Greater Scaup will eat seeds, leaves, stems and roots, along with sedges, pondweeds, muskgrass, and wild celery. Owing to the Greater Scaup's webbed feet and weight, it can dive up to 6 metres (20 ft) and stay submerged for up to a minute, allowing it to reach food sources that are unobtainable to other diving ducks. The Greater Scaup forms large flocks, some of which can contain thousands of birds. When flocks are in water, they will face the current, and as the ducks float backwards, some fly to the front of the flock to maintain position.
Threats: Common predators of the Greater Scaup are owls, skunks, raccoons, foxes, coyotes, and humans. Greater Scaup often find themselves entangled in fishing nets, thus large numbers of them drown in nets each year. Greater Scaup can catch avian influenza, so future outbreaks have the potential to threaten Greater Scaup populations.
Although the Greater Scaup faces numerous threats, the most significant challenge to their survival is habitat degradation caused by a mix of human development and runoff.  Greater Scaup, when moulting and during the winter, are threatened by escalated levels of organochloride contaminants. Oil and sewage pollution also threaten this duck. Since 80% of the Greater Scaup population winters in the urbanized part of the Atlantic Flyway, these ducks are subject to high levels of organic contaminates, along with increased levels of heavy metals in foods and habitat."/></a>
            <a href=""><img src="../images/Clangula_hyemalis.jpg" data-big="../images/Clangula_hyemalis.jpg"
                            data-title="Long-tailed Duck (Clangula hyemalis)"
                            data-description="The Long-tailed Duck or Oldsquaw (Clangula hyemalis) is a medium-sized sea duck. It is the only living member of its genus, Clangula; this was formerly used for the goldeneyes, with the Long-tailed Duck being placed in Harelda. 
Adults have white underparts, though the rest of the plumage goes through a complex moulting process. The male has a long pointed tail (10 to 15 cm (3.9 to 5.9 in)) and a dark grey bill crossed by a pink band. In winter, the male has a dark cheek patch on a mainly white head and neck, a dark breast and mostly white body. In summer, the male is dark on the head, neck and back with a white cheek patch. The female has a brown back and a relatively short pointed tail. In winter, the female's head and neck are white with a dark crown. In summer, the head is dark. Juveniles resemble adult females in autumn plumage, though with a lighter, less distinct cheek patch.
Their breeding habitat is in tundra pools and marshes, but also along sea coasts and in large mountain lakes in the North Atlantic region, Alaska, northern Canada, northern Europe and Russia. The nest is located on the ground near water; it is built using vegetation and lined with down. They are migratory and winter along the eastern and western coasts of North America, on the Great Lakes, coastal northern Europe and Asia, with stragglers to the Black Sea. The most important wintering area is the Baltic Sea, where a total of about 4.5 million gather.
The Long-tailed Duck is gregarious, forming large flocks in winter and during migration. They feed by diving for mollusks, crustaceans and some small fish. Although they usually feed close to the surface, they are capable of diving to depths of 60 m (200 ft).
In North American English it is sometimes called Oldsquaw, though this name has fallen out of favour under influence of negative connotations of the word squaw in English usage. Some biologists have also feared that this name would be offensive to some Native American tribes involved in the conservation effort. The American Ornithologists' Union stated that 'political correctness' was not sufficient to change the name, but 'to conform with English usage in other parts of the world', it officially adopted the name Long-tailed Duck.
The males are vocal and have a musical yodelling call ow, ow, owal-ow. Protected species in Bulgaria."/></a>
            <a href=""><img src="../images/Melanitta_fusca.jpg" data-big="../images/Melanitta_fusca.jpg" 
                            data-title="Velvet Scoter (Melanitta fusca)"
                            data-description="The Velvet Scoter (Melanitta fusca), also called a Velvet Duck or whitewing[citation needed] (not to be confused with the White-winged Scoter), is a large sea duck, which breeds over the far north of Europe and Asia west of the Yenisey basin. A small, isolated population nests in eastern Turkey. The East Siberian and North American White-winged Scoter is sometimes considered conspecific with the Velvet Scoter, and its two constituent subspecies are then known as M. f. stejnegeri and M. f. deglandi. Velvet and White-winged Scoter, along with the Surf Scoter, are placed in the subgenus Melanitta, distinct from the subgenus Oidemia, Black and Common Scoters.
It winters further south in temperate zones, Europe as far south as Great Britain, and on the Black and Caspian Sea. Small numbers reach France and northern Spain. It forms large flocks on suitable coastal waters. These are tightly packed, and the birds tend to take off together.
The lined nest is built on the ground close to the sea, lakes or rivers, in woodland or tundra, and typically contains 7–9 eggs. This duck dives for crustaceans and molluscs.
It is characterised by its bulky shape and large bill. It is the largest scoter at 51–58 cm. The male is all black, except for white around the eye and a white speculum. It has a bulbous yellow bill with a black base. The females are brown birds with two pale patches on each side of the head and white wing patches.
The Velvet Scoter is one of the species to which the Agreement on the Conservation of African-Eurasian Migratory Waterbirds (AEWA) applies. Protected species in Bulgaria."/></a>
            <a href=""><img src="../images/Vanellus_leucurus.jpg" data-big="../images/Vanellus_leucurus.jpg"
                            data-title="White-tailed Lapwing (Vanellus leucurus)" 
                            data-description="The White-tailed Lapwing or White-tailed Plover (Vanellus leucurus) is a wader in the lapwing genus.
It breeds semi-colonially on inland marshes in Iraq, Iran and southern Russia. Four eggs are laid in a ground nest. The Iraqi and Iranian breeders are mainly residents, but Russian birds migrate south in winter to the Indian Subcontinent, the Middle East and north east Africa. It is a very rare vagrant in western Europe, the first example in Britain being found at Packington, Warwickshire on 12 July 1975.
This medium-sized lapwing is long-legged and fairly long-billed. It is the only lapwing likely to be seen in other than very shallow water, where it picks insects and other small prey mainly from the surface.
Adults are slim erect birds with a brown back and foreneck, paler face and grey breast. Its long yellow legs, pure white tail and distinctive brown, white and black wings make this species unmistakable. Young birds have a scaly back, and may show some brown in the tail.
The breeding season call is a peewit, similar to Northern Lapwing.
The White-tailed Lapwing is one of the species to which the Agreement on the Conservation of African-Eurasian Migratory Waterbirds (AEWA) applies. Observed for the first time in Bulgaria in the wetlands around Sofia."/></a>
            <a href=""><img src="../images/Gelochelidon_nilotica.jpg" data-big="../images/Gelochelidon_nilotica.jpg"
                                                     data-title="Gull-billed Tern (Gelochelidon nilotica)" 
                                                     data-description="The Gull-billed Tern (Gelochelidon nilotica) formerly Sterna nilotica (Bridge et al., 2005), is a seabird of the tern family Sternidae. It is now considered to be in its own genus.
This is a fairly large and powerful tern, similar in size and general appearance to a Sandwich Tern, but the short thick gull-like bill, broad wings, long legs and robust body are distinctive. The summer adult has grey upperparts, white underparts, a black cap, strong black bill and black legs. The call is a characteristic ker-wik. It is 33–42 cm (13–17 in) in length and 76–91 cm (30–36 in) in wingspan. Body mass ranges from 150–292 g (5.3–10.3 oz).
In winter, the cap is lost, and there is a dark patch through the eye like a Forster's Tern or a Mediterranean Gull. Juvenile Gull-billed Terns have a fainter mask, but otherwise look much like winter adults.
Juvenile Sandwich Terns have a short bill, and are frequently mistaken for Gull-billed Tern where the latter species is uncommon, such as North Sea coasts.
This species breeds in colonies on lakes, marshes and coasts. It nests in a ground scrape and lays two to five eggs. While widely distributed in freshwater areas in Eurasia, it is associated almost solely with saltwater, coastal areas in North America.
This is a somewhat atypical tern, in appearance like a Sterna tern, but with feeding habits more like the Chlidonias marsh terns, Black Tern and White-winged Tern. It used to be grouped in the genus Sterna but is now placed on its own in the genus Gelochelidon.
The Gull-billed Tern does not normally plunge dive for fish like the other white terns, and has a broader diet than most other terns. It largely feeds on insects taken in flight, and also often hunts over wet fields and even in brushy areas, to take amphibians and small mammals, as well as small birds and the chicks and eggs of other terns. It is also an opportunistic feeder, and has been observed to pickup and feed on dead dragonflies from the road."/></a>
           <a href=""><img src="../images/Calidris_canutus.jpg" data-big="../images/Calidris_canutus.jpg" 
                            data-title="Red Knot (Calidris canutus)" 
                            data-description="The Red Knot (Calidris canutus) (just Knot in Europe) is a medium sized shorebird which breeds in tundra and the Arctic Cordillera in the far north of Canada, Europe, and Russia. It is a large member of the Calidris sandpipers, second only to the Great Knot. Six subspecies are recognised.
Their diet varies according to season; arthropods and larvae are the preferred food items at the breeding grounds, while various hard-shelled molluscs are consumed at other feeding sites at other times. North American breeders migrate to coastal areas in Europe and South America, while the Eurasian populations winter in Africa, Papua New Guinea, Australia, and New Zealand. This species forms enormous flocks when not breeding.
In the breeding season the Red Knot has a circumpolar distribution in the high Arctic, then migrates to coasts around the world from 50° N to 58° S. The red knot has one of the longest migrations of any bird. Every year it travels more than 9,000 miles from the Arctic to the southern tip of South America. The exact migration routes and wintering grounds of individual subspecies are still somewhat uncertain. The nominate race C. c. canutus breeds in the Taymyr Peninsula and possibly Yakutia and migrates to the Western Europe and then down to western and southern Africa. C. c. rogersi breeds in the Chukchi Peninsula in eastern Siberia, and winters in eastern Australia and New Zealand. Small and declining numbers of rogersi (but possibly of the later described piersmai) winter in the mudflats in the Gulf of Mannar and on the eastern coast of India. The recently split race C. c. piersmai breeds in the New Siberian Islands and winters in north-western Australia. C. c. roselaari breeds in Wrangel Island in Siberia and north-western Alaska, and it apparently winters in Florida, Panama and Venezuela. C. c. rufa breeds in the Canadian low Arctic, and winters South America, and C. c. islandica breeds in the Canadian high Arctic as well as Greenland, and winters in Western Europe.
Birds wintering in west Africa were found to restrict their daily foraging to a range of just 2–16 km2 of intertidal area and roosted a single site for several months. In temperate regions such as the Wadden Sea they have been found to change roost sites each week and their feeding range may be as much as 800 km2 during the course of a week.
An adult Red Knot is the second largest Calidris sandpiper, measuring 23–26 cm (9–10 in) long with a 47–53 cm (18.5–21 in) wingspan. The body shape is typical for the genus, with a small head and eyes, a short neck and a slightly tapering bill that is no longer than its head. It has short dark legs and a medium thin dark bill. The winter, or basic, plumage becomes uniformly pale grey, and is similar between the sexes. The alternate, or breeding, plumage is mottled grey on top with a cinnamon face, throat and breast and light-coloured rear belly. The alternate plumage of females is similar to that of the male except it is slightly lighter and the eye-line is less distinct. canutus, islandica and piersmai are the 'darker' subspecies. Subspecies rogersi has a lighter belly than either roselaari or piersmai, and rufa is the lightest in overall plumage. The transition from alternate to basic plumages begins at the breeding site but is most pronounced during the southwards migration. The molt to alternate plumage begins just prior to the northwards migration to the breeding grounds, but is mostly during the migration period.
The large size, white wing bar and grey rump and tail make it easy to identify in flight. When feeding the short dark green legs give it a characteristic 'low-slung' appearance. When foraging singly, they rarely call, but when flying in a flock they make a low monosyllabic knutt and when migrating they utter a disyllabic knuup-knuup. They breed in the moist tundra during June to August. The display song of the male is a fluty poor-me. The display includes circling high with quivering wing beats and tumbling to the ground with the wings held upward. Both sexes incubate the eggs, but the female leaves parental care to the male once the eggs have hatched.
Juvenile birds have distinctive submarginal lines and brown coverts during the first year. In the breeding season the males can be separated with difficulty (<80% accuracy in comparison to molecular methods) based on the more even shade of the red underparts that extend towards the rear of the belly.
On the breeding grounds, Knots eat mostly spiders, arthropods, and larvae obtained by surface pecking, and on the wintering and migratory grounds they eat a variety of hard-shelled prey such as bivalves, gastropods and small crabs that are ingested whole and crushed by a muscular stomach.
The Red Knot is territorial and seasonally monogamous; it is unknown if pairs remain together from season to season. Males and females breeding in Russia have been shown to exhibit site fidelity towards their breeding locales from year to year, but there is no evidence as to whether they exhibit territorial fidelity. Males arrive before females after migration and begin defending territories. As soon as males arrive, they begin displaying, and aggressively defending their territory from other males.
The Red Knot nests on the ground, near water, and usually inland. The nest is a shallow scrape lined with leaves, lichens and moss. Males construct three to five nest scrapes in their territories prior to the arrival of the females. The female lays three or more usually four eggs, apparently laid over the course of six days. The eggs measure 43 x 30 mm (1.7 x 1.2 in) in size and are ground coloured, light olive to deep olive buff, with a slight gloss. Both parents incubate the eggs, sharing the duties equally. The off duty parent forages in flocks with others of the same species. The incubation period lasting around 22 days. At early stages of incubation the adults are easily flushed from the nest by the presence of humans near the nest, and may not return for several hours after being flushed. However in later stages of incubation they will stay fast on the eggs. Hatching of the clutch is usually synchronised. The chicks are precocial at hatching, covered in downy cryptic feathers. The chicks and the parents move away from the nest within a day of hatching and begin foraging with their parents. The female leaves before the young fledge while the males stay on. After the young have fledged, the male begins his migration south and the young make their first migration on their own."/></a>
            <a href=""><img src="../images/Calidris_maritima.jpg" data-big="../images/Calidris_maritima.jpg"
                            data-title="Purple Sandpiper (Calidris maritima)"
                            data-description="The Purple Sandpiper (Calidris maritima) is a small shorebird. Adults have short yellow legs and a medium thin dark bill with a yellow base. The body is dark on top with a slight purplish gloss and mainly white underneath. The breast is smeared with grey and the rump is black. They measure 20–22 cm (7.9–8.7 in) in length and 42–46 cm (17–18 in) across the wings, and weight is from 50–105 g (1.8–3.7 oz). 
Their breeding habitat is the northern tundra on Arctic islands in Canada and coastal areas in Greenland and northwestern Europe. They nest on the ground either elevated on rocks or in lower damp location. The males makes several scrapes; the female choose one and lays 3 or 4 eggs. The male takes the major responsibility for incubation and tends the chicks. The young feed themselves.
They are late migrants and move to rocky ice-free Atlantic coasts in winter. most go no further south than North Carolina and northern Portugal. They are fairly gregarious, forming small flocks, often with Ruddy Turnstones. This species is tame and approachable.
These birds forage on rocky coasts, picking up food by sight. They mainly eat arthropods and mollusks, also some plant material.
The Purple Sandpiper is one of the species to which the Agreement on the Conservation of African-Eurasian Migratory Waterbirds (AEWA) applies." data-link=""/></a>
        </div>
        
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js"></script>
        <script src="../js/galleria-1.3.5.js"></script>
        <script>
            Galleria.loadTheme('../js/galleria.classic.js');
            Galleria.run('.galleria');
        </script>
    </body>
</html>